name: swift-ring-checker 
version: 1.2
summary: Check swift rings in Juju-deployed Swift cluster.
description: >
   This package provides swift-ring-checker. Run this tool against
   a Juju deployed Swift cluster and it will display md5sum of your
   rings and builders to allow visual analysis of consistency
   across your cluster. Also runs swift-ring-builder on builders to
   display config and checks if services are running.
confinement: strict
grade: devel
base: core18

apps:
  swift-ring-checker:
    command: swift-ring-checker.sh
    plugs: [home, network, juju-client-observe]
parts:
  swift-ring-checker:
    source: .
    plugin: dump
    stage-packages: [jq, juju]
